@echo off
echo Zipping up the Orphan drivers into ORPHAN.ZIP and then deleting
echo them from this main directory.
pkzip orphan ibmbak.com ibmsnd.com adlib.com vmsnd.com smsnd.com digisp.com tanextx.com echoii.com lantsnd.com ibm1bit.com bigmouth.com
del ibmbak.com
del ibmsnd.com
del adlib.com
del vmsnd.com
del smsnd.com
del digisp.com
del tanextx.com
del echoii.com
del lantsnd.com
del ibm1bit.com
del bigmouth.com
